# Generated by Django 5.2.13 on 2026-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
