# Generated by Django 5.2.13 on 2026-04-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_expiration_date_task_task_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_expiration_date',
            new_name='expiration_date',
        ),
    ]
